-- Add RPG status columns to users table
ALTER TABLE users ADD COLUMN level INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN xp INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN status_points INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN stat_str INTEGER DEFAULT 10;
ALTER TABLE users ADD COLUMN stat_agi INTEGER DEFAULT 10;
ALTER TABLE users ADD COLUMN stat_def INTEGER DEFAULT 10;
ALTER TABLE users ADD COLUMN stat_vit INTEGER DEFAULT 10;

-- Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  is_read INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
