#:schema node_modules/wrangler/config-schema.json
name = "my-app-backend"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "physiproof-db"
database_id = "d0380ad0-d78d-4318-87b1-6ea4fe86012e"
migrations_dir = "migrations"

[vars]
GEMINI_API_KEY = "AQ.Ab8RN6JwIMsrJcvFy6QPPopK1bvQRmRPje6zQquepSApPYRZXQ"
